### PR TITLE
libusb1: provide a second context that uses USBDK

### PR DESCRIPTION
**Pull request by jonasmalacofilho**

### CODE REVIEW

**Comment by mcuee** [comment]
The patch is apparently okay, but I can not get usbdk to work with or without this pull request as mentioned in #200, strange.

**Comment by mcuee** [comment]
As mentioned in #200, this change itself is good, but some other changes are required for usbdk to work under Windows, due to the behavior of usbdk driver (it is a filter driver).

**Comment by mcuee** [comment]
I think we can close this PR.
https://github.com/daynix/UsbDk/issues

usbdk seems to casue quite some stability issues and it has not been updated for quite a while. I have updated libusb Wiki to discourage the use of usbdk.
https://github.com/libusb/libusb/wiki/Windows#user-content-Driver_Installation
https://github.com/libusb/libusb/wiki/FAQ#user-content-What_about_usbdk

**Comment by jonasmalacofilho** [comment]
Ack, and closing as suggested. Thanks.

**Pull request closed without merging**
